apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb-deployment
spec:
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
        - name: mongodb
          image: mongo:4.2.8
          ports:
            - containerPort: 27017
          envFrom:
            - secretRef:
                name: mongodb-secret
          resources:
            requests:
              memory: "512Mi"   # Aumentar as solicitações de memória
              cpu: "1000m"
            limits:
              memory: "512Mi"     # Aumentar os limites de memória
              cpu: "1000m"
          volumeMounts:
            - mountPath: /data/db
              name: mongo-data              
      volumes:
        - name: mongo-data
          persistentVolumeClaim:
            claimName: host-pvc
